name: cove
recipe: drupal10
config:
  php: "8.3"
  drush: ^11
  composer_version: 2-latest
  webroot: web
  database: mysql:8.0

services:
  database:
    type: mysql:8.0
    creds:
      user: drupal
      password: drupal
      database: drupal
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'https://cove.lndo.site'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
